# Generated by Django 4.0 on 2021-12-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_service_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('Face', 'Full Face'), ('Body', 'Full body'), ('Pack', 'Full packages')], max_length=4),
        ),
    ]
