# Generated by Django 4.0 on 2021-12-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_service_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('Pack', 'Full packages'), ('Body', 'Full body'), ('Face', 'Full Face')], max_length=4),
        ),
    ]
