# Generated by Django 4.0 on 2021-12-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_service_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='length',
        ),
        migrations.AddField(
            model_name='service',
            name='time',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('SKIN', 'Skin'), ('NON_INV', 'Non-invasive procedure'), ('HEALTH', 'Health'), ('APP', 'Appearance')], default='SKIN', max_length=7),
        ),
    ]
