# Generated by Django 4.0 on 2021-12-25 21:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_booking_phone_alter_service_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='time_from',
        ),
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Starting date/time of booking'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='time_to',
            field=models.TimeField(verbose_name='Ending date/time of booking'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('SKIN', 'Skin'), ('NON_INV', 'Non-invasive procedure'), ('APP', 'Appearance'), ('HEALTH', 'Health')], default='SKIN', max_length=7),
        ),
    ]
