# Generated by Django 4.0 on 2021-12-26 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_remove_booking_time_from_booking_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('SKIN', 'Skin'), ('NON_INV', 'Non-invasive procedure'), ('HEALTH', 'Health'), ('APP', 'Appearance')], default='SKIN', max_length=7),
        ),
    ]
