# Generated by Django 4.0 on 2021-12-26 18:06

from django.db import migrations, models
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_alter_service_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='phone',
        ),
        migrations.AddField(
            model_name='booking',
            name='POSTCODE',
            field=models.CharField(default=None, max_length=8, verbose_name='Post Code'),
        ),
        migrations.AddField(
            model_name='booking',
            name='city',
            field=models.CharField(default=None, max_length=10, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='booking',
            name='county',
            field=models.CharField(default=None, max_length=20, verbose_name='County'),
        ),
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.CharField(default=None, max_length=30, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='address',
            field=models.CharField(max_length=20, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_id',
            field=models.CharField(default=website.models.randomProdID, max_length=8, verbose_name='Booking ID for user'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('APP', 'Appearance'), ('SKIN', 'Skin'), ('NON_INV', 'Non-invasive procedure'), ('HEALTH', 'Health')], default='SKIN', max_length=7),
        ),
    ]
