# Generated by Django 4.0 on 2021-12-26 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_remove_booking_phone_booking_postcode_booking_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='time_to',
        ),
        migrations.AddField(
            model_name='booking',
            name='Time_From',
            field=models.TimeField(default=None, verbose_name='Ending date/time of booking'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(default=None, verbose_name='Starting date'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('APP', 'Appearance'), ('HEALTH', 'Health'), ('NON_INV', 'Non-invasive procedure'), ('SKIN', 'Skin')], default='SKIN', max_length=7),
        ),
    ]
