# Generated by Django 4.0 on 2021-12-26 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_remove_booking_time_to_booking_time_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='service',
        ),
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.ManyToManyField(related_name='service', to='website.Service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('SKIN', 'Skin'), ('HEALTH', 'Health'), ('APP', 'Appearance'), ('NON_INV', 'Non-invasive procedure')], default='SKIN', max_length=7),
        ),
    ]
