# Generated by Django 4.0 on 2021-12-26 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_remove_booking_service_booking_service_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(default=None, max_length=20, verbose_name='Full Name: ')),
                ('email', models.CharField(default=None, max_length=30, verbose_name='Email')),
                ('phone', models.CharField(default=None, max_length=11, verbose_name='Phone')),
                ('POSTCODE', models.CharField(default=None, max_length=8, verbose_name='Post Code')),
                ('address', models.CharField(max_length=20, verbose_name='Address')),
            ],
        ),
        migrations.RemoveField(
            model_name='booking',
            name='POSTCODE',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='address',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='city',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='county',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='email',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='lastName',
        ),
        migrations.AlterField(
            model_name='booking',
            name='Time_From',
            field=models.TimeField(default=None, verbose_name='Booking Time'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(default=None, verbose_name='Booking Date: '),
        ),
        migrations.RemoveField(
            model_name='booking',
            name='service',
        ),
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service', to='website.service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('SKIN', 'Skin'), ('NON_INV', 'Non-invasive procedure'), ('APP', 'Appearance'), ('HEALTH', 'Health')], default='SKIN', max_length=7),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.customer'),
        ),
    ]
