# Generated by Django 4.0 on 2021-12-26 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_customer_remove_booking_postcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('APP', 'Appearance'), ('NON_INV', 'Non-invasive procedure'), ('HEALTH', 'Health'), ('SKIN', 'Skin')], default='SKIN', max_length=7),
        ),
    ]
