# Generated by Django 4.0 on 2021-12-27 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_alter_service_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('NON_INV', 'Non-invasive procedure'), ('SKIN', 'Skin'), ('HEALTH', 'Health'), ('APP', 'Appearance')], default='SKIN', max_length=7),
        ),
    ]
