# Generated by Django 4.0 on 2021-12-29 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_available_day_remove_booking_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('NON_INV', 'Non-invasive procedure'), ('HEALTH', 'Health'), ('APP', 'Appearance'), ('SKIN', 'Skin')], default='SKIN', max_length=7),
        ),
    ]
