# Generated by Django 4.0 on 2021-12-29 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_alter_service_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='available_day',
            name='days',
            field=models.DateField(verbose_name='Create Available Dates'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='Time_From',
            field=models.IntegerField(choices=[(0, '09:00'), (1, '10:30'), (2, '11:00'), (3, '11:30'), (4, '12:00'), (5, '12:30'), (6, '13:00'), (7, '13:30'), (8, '14:00'), (9, '14:30'), (10, '15:00'), (11, '15:30'), (12, '16:00'), (13, '16:30'), (14, '17:00'), (15, '17:30'), (16, '18:00'), (17, '18:30'), (18, '19:00')]),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('NON_INV', 'Non-invasive procedure'), ('APP', 'Appearance'), ('SKIN', 'Skin'), ('HEALTH', 'Health')], default='SKIN', max_length=7),
        ),
        migrations.AlterField(
            model_name='service',
            name='time',
            field=models.IntegerField(default=1),
        ),
    ]
