# Generated by Django 4.0 on 2021-12-30 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_alter_available_day_days_alter_booking_time_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='slot_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='service',
            name='time',
            field=models.IntegerField(default=30, help_text='Time only 30 minutes and 60 minutes allowed.'),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('date', 'Time_From')},
        ),
    ]
