# Generated by Django 4.0 on 2021-12-31 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0037_alter_customer_email_alter_service_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('NON_INV', 'Non-invasive procedure'), ('SKIN', 'Skin'), ('APP', 'Appearance'), ('HEALTH', 'Health')], default='SKIN', max_length=7),
        ),
        migrations.AlterModelTable(
            name='available_day',
            table='Days',
        ),
    ]
