# Generated by Django 4.0 on 2021-12-31 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0038_alter_service_category_alter_available_day_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('SKIN', 'Skin'), ('HEALTH', 'Health'), ('NON_INV', 'Non-invasive procedure'), ('APP', 'Appearance')], default='SKIN', max_length=7),
        ),
    ]
