# Generated by Django 4.0 on 2021-12-31 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0041_remove_customer_postcode_remove_customer_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('APP', 'Appearance'), ('NON_INV', 'Non-invasive procedure'), ('SKIN', 'Skin'), ('HEALTH', 'Health')], default='SKIN', max_length=7),
        ),
    ]
