# Generated by Django 4.0 on 2022-01-04 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0049_remove_order_service_alter_service_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='totalpaid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('SKIN', 'Skin'), ('HEALTH', 'Health'), ('APP', 'Appearance'), ('NON_INV', 'Non-invasive procedure')], default='SKIN', max_length=7),
        ),
    ]
