# Generated by Django 4.0 on 2022-01-22 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0050_order_totalpaid_alter_service_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='transaction_id',
            field=models.CharField(default=None, max_length=10, verbose_name='Order ID'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('HEALTH', 'Health'), ('NON_INV', 'Non-invasive procedure'), ('APP', 'Appearance'), ('SKIN', 'Skin')], default='SKIN', max_length=7),
        ),
    ]
