# Generated by Django 4.0 on 2022-01-22 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0051_alter_orderitem_transaction_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='complete',
            new_name='billing_status',
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('HEALTH', 'Health'), ('SKIN', 'Skin'), ('NON_INV', 'Non-invasive procedure'), ('APP', 'Appearance')], default='SKIN', max_length=7),
        ),
    ]
