# Generated by Django 4.0 on 2022-02-15 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0053_available_day_finish_available_day_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='available_day',
            name='finish',
            field=models.IntegerField(choices=[(0, '09:00'), (1, '09:30'), (2, '10:00'), (3, '10:30'), (4, '11:00'), (5, '11:30'), (6, '12:00'), (7, '12:30'), (8, '13:00'), (9, '13:30'), (10, '14:00'), (11, '14:30'), (12, '15:00'), (13, '15:30'), (14, '16:00'), (15, '16:30'), (16, '17:00'), (17, '17:30'), (18, '18:00')], default=18),
        ),
        migrations.AlterField(
            model_name='available_day',
            name='start',
            field=models.IntegerField(choices=[(0, '09:00'), (1, '09:30'), (2, '10:00'), (3, '10:30'), (4, '11:00'), (5, '11:30'), (6, '12:00'), (7, '12:30'), (8, '13:00'), (9, '13:30'), (10, '14:00'), (11, '14:30'), (12, '15:00'), (13, '15:30'), (14, '16:00'), (15, '16:30'), (16, '17:00'), (17, '17:30'), (18, '18:00')], default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='Time_From',
            field=models.IntegerField(choices=[(0, '09:00'), (1, '09:30'), (2, '10:00'), (3, '10:30'), (4, '11:00'), (5, '11:30'), (6, '12:00'), (7, '12:30'), (8, '13:00'), (9, '13:30'), (10, '14:00'), (11, '14:30'), (12, '15:00'), (13, '15:30'), (14, '16:00'), (15, '16:30'), (16, '17:00'), (17, '17:30'), (18, '18:00')]),
        ),
    ]
