# Generated by Django 4.0 on 2022-02-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0054_alter_available_day_finish_alter_available_day_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('HEALTH', 'Health'), ('APP', 'Appearance'), ('NON_INV', 'Non-invasive procedure'), ('SKIN', 'Skin')], default='SKIN', max_length=7),
        ),
    ]
