# Generated by Django 4.0 on 2022-02-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0055_alter_service_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('NON_INV', 'Non-invasive procedure'), ('APP', 'Appearance'), ('HEALTH', 'Health'), ('SKIN', 'Skin')], default='SKIN', max_length=7),
        ),
    ]
