# Generated by Django 4.0 on 2022-02-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0057_alter_service_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='available_day',
            name='finish',
        ),
        migrations.RemoveField(
            model_name='available_day',
            name='start',
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('NON_INV', 'Non-invasive procedure'), ('APP', 'Appearance'), ('SKIN', 'Skin'), ('HEALTH', 'Health')], default='SKIN', max_length=7),
        ),
    ]
