# Generated by Django 4.0 on 2022-03-05 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0063_alter_service_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('HEALTH', 'Health'), ('APP', 'Appearance'), ('NON_INV', 'Non-invasive procedure'), ('SKIN', 'Skin')], default='SKIN', max_length=7),
        ),
    ]
