# Generated by Django 4.0 on 2022-03-05 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0115_alter_service_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='billing_status',
            new_name='complete',
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('APP', 'Appearance'), ('NON_INV', 'Non-invasive procedure'), ('SKIN', 'Skin'), ('HEALTH', 'Health')], default='SKIN', max_length=7),
        ),
    ]
